export enum Family {
    BRAKING = 'Braking',
    FILTRATION = 'Filtration',
    ENGINE = 'Engine',
    CLUTCH = 'Clutch',
    GEARBOX = 'Gearbox',
    UNIVERSAL_JOINTS = 'Universal_Joints',
    START_LOAD = 'Start_Load',
    EXHAUST = 'Exhaust',
    STEERING = 'Steering',
    Suspension = 'Suspension',
    BEARINGS = 'Bearings',
    VISIBILITY = 'Visibility',
    HEATING_AND_AIR_CONDITIONING = 'Heating_and_air_conditioning',
    INTERIOR = 'Interior',
    ACCESSORIES_AND_CARRYING = 'Accessories_and_Carrying',
    WHEELS_RIMS = 'Wheels_Rims',
    CAR_BODY = 'Car_Body',
}